[project]
name = "se-prices"
version = "1.0.0"
description = "Trends of registration fees for the major software engineering conferences."
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "plotnine>=0.14.1",
]
